### ISSUE TITLE
How to Prepare for CO 23.0.0 after 22 + CXPatcher

### ISSUE THREAD

**Issue by kaldown** [italomandara/CXPatcher#100]
I just recently removed every occurrence of CrossOver after using `fd crossover` and Installed version 23.
Can I move my bottles from version 22 to 23?
Or there are libraries that being injected and I have to freshly install steam and the rest of the games on new version?

Thank you

**Comment by italomandara** [comment]
Always create a new bottle and if you're still using CX22 ever so often, have separate bottles.
