### ISSUE TITLE
Feature Suggestion: allow lower case letters when typing the codeweavers disclaimer and allow use of enter key to submit disclaimer

### ISSUE THREAD

**Issue by macprotips** [italomandara/CXPatcher#106]
I think that allowing lower case letters when typing the codeweavers disclaimer and allowing the use of the enter key to submit the disclaimer would make the cxpatcher "login" easier but just as effective! Thanks!

**Comment by italomandara** [comment]
Implemented in https://github.com/italomandara/CXPatcher/pull/113
