### ISSUE TITLE
Is it possible to make  DX11 application  to be run through GPTK?

### ISSUE THREAD

**Issue by SuddenDeathMP** [italomandara/CXPatcher#116]
DX11 games  after applying CXPatcher not working without DXVK (raised error: DX11 Engine api level sould be above 10.0), so i assume it is GPTK for DX12 applications only.
In my case game is required Geometry shaders as it is  on UE4 and it is not looking good on DXVK

**Comment by italomandara** [comment]
No there are many dx11 games that can run via gptk, but there are also dx11 games that don't because gptk is still a beta after all to get the most of crossover have 2 copies of cx one patched with gptk and one without

**Comment by SuddenDeathMP** [comment]
> No there are many dx11 games that can run via gptk, but there are also dx11 games that don't because gptk is still a beta after all. To get the most of crossover have 2 copies of cx one patched with gptk and one without

I did patch mine with GPTK, but it seems not utilising it for DX11, so i get engine api level error

**Comment by italomandara** [comment]
I can play titanfall2 with gptk that's dx11 so maybe that particular game has some extension that's not yet covered in gptk beta

**Comment by SuddenDeathMP** [comment]
I delete all instances of crossover, wiped all bottles, and installed everything from scratch and it working now for me!!! game: Foxhole

**Comment by italomandara** [comment]
closing this for not being a CXPatcher bug if you have further questions please use https://github.com/italomandara/CXPatcher/discussions
