### ISSUE TITLE
CXPatcher V0.3.1 - In game HUD and minimap no longer works when launching Baldurs Gate 3 through Steam

### ISSUE THREAD

**Issue by fredrile** [italomandara/CXPatcher#118]
Issue may affect other games as well. Worked fine on V0.3.0.

FPS counter now works. No difference if on/off

Steps to reproduce:
- Download and install Crossover 22.1.1. Apply CXpatcher V0.3.0
- Download and install BG3 (GOG version) and add to Steam library manually
- Upgrade to CXpatcher V0.3.1
- Launch and play BG3
- Observe black minimap and no HUD

Thanks!

**Comment by italomandara** [comment]
screenshots? your setup + system info? logs? please?

**Comment by fredrile** [comment]
Macbook pro 14 inch 2021 - Apple M1 Pro + 16GB
macOS Sonoma 14.0 (23A339) (Beta)

Attached screen shot and a Crossover logfile. Let me know if you need anything else!

![Screenshot 2023-09-15 at 18 15 54](https://github.com/italomandara/CXPatcher/assets/97180944/d9577e3e-1333-4b24-96bd-3f1e7a7a35f5)
[Steam 2.cxlog.zip](https://github.com/italomandara/CXPatcher/files/12621757/Steam.2.cxlog.zip)

**Comment by italomandara** [comment]
are you using dxvk? gptk? or none of them?

**Comment by italomandara** [comment]
From the logs can't see any logs from gptk... strange

**Comment by fredrile** [comment]
Thank you. I fixed it by reapplied the patch, making sure the option to integrate D3DMetal (GPTK) was switched on. I guess my brain assumed it would already be there since it was already installed with 0.3.0
