### ISSUE TITLE
Halo Infinite Doesnt Launch

### ISSUE THREAD

**Issue by Mrblutziii** [italomandara/CXPatcher#123]
Hi, So I just recently started messing around with Crossover and CXPatcher. Trying out different games and I am unable to get Halo Infinite to launch through steam. I suspected it might work due to the fact that it now should support Directx12. But perhaps this is due to it being a Microsoft game and I know there are heavy limitations to their games? 

Any assistance would be helpful!

**Comment by italomandara** [comment]
Did you try patching with GPTK enabled? that should give you DX12 support to some extent.

**NOTE:** Halo infinite uses Microsoft in-house [anti cheat](https://www.halowaypoint.com/news/closer-look-halo-infinites-anti-cheat-strategy) which could detect crossover and just quit immediately.
