### ISSUE TITLE
Rockstar Launcher doesnt log me in

### ISSUE THREAD

**Issue by sshrmr** [italomandara/CXPatcher#124]
After using the CXPatcher, the Rockstar Launcher logs out and doesnt let me log back in with all the correct login info. Always says the email or password is incorrect. As soon as i reinstall CrossOver without the CXPatcher - i can successfully log in. What can be the issue?

MacOS Sonoma Developer Beta 14.0
CrossOver 22.1.1

**Comment by italomandara** [comment]
Never heard of this issue before, have you tried using a completely new bottle after patching?

**Comment by sshrmr** [comment]
> Never heard of this issue before, have you tried using a completely new bottle after patching?

Nope, I’ll try and let u know👌🏻🙏🏻

**Comment by sshrmr** [comment]
> Never heard of this issue before, have you tried using a completely new bottle after patching?

Hey again, thanks, it did work! Weird thing now - if i run the game from Heroic it starts a separate copy of Rockstar Launcher, and this version doesnt detect my controller (that worked perfectly before CXPatcher). Am i doing something wrong?

**Comment by italomandara** [comment]
Ok since lots of users are having issues with bottles created with the unpatched crossover I'm going to release a new version that also changes the default bottle path
