### ISSUE TITLE
[Inquiry] CXPatcher - Repatch

### ISSUE THREAD

**Issue by Laicure** [italomandara/CXPatcher#13]
Is there an instruction wherein if you release an update, you do a "repatch" of CrossOver?

Like... I patched my CX on ver 0.2.9 and then by next week, you released 0.2.10, should I do the usual download -> drag and drop or do I need to do something else?

**Comment by italomandara** [comment]
> Is there an instruction wherein if you release an update, you do a "repatch" of CrossOver?
> 
> Like... I patched my CX on ver 0.2.9 and then by next week, you released 0.2.10, should I do the usual download -> drag and drop or do I need to do something else?

I will add a repatch feature soon sorry but i have been busy with color profiles implementation, right now what you can do is restore first and then patch again.

**Comment by Laicure** [comment]
no worries, restore then patch will do, thanks for clearing that up ;)
