### ISSUE TITLE
CXPatcher v0.3.3 wont open after download

### ISSUE THREAD

**Issue by IvanGoya** [italomandara/CXPatcher#131]
my m1 pro wont allow me to open cxpatcher, I downloaded the latest version(0.3.3) and when trying to open it I get the message "“CXPatcher” will damage your computer. You should move it to the Trash." I have also tried running the command " xattr -cr /Applications/CXPatcher.app " which returns " No such file: "

I asked for help on this issue in the AppleGamingWiki discord support channel, and it seems one of the mac developers in there is also having the same issue

**Comment by italomandara** [comment]
when you are using the xattr command you're putting the wrong path
start writing `xattr -cr` and then drag your CXPatcher app in that terminal window to get the right one.
 
It could be that my signing certificate is expired, I'll fix that in the next release.

**Comment by AyAyRON123** [comment]
I am also having this issue and using @italomandara fix didnt seem to work.

**Comment by italomandara** [comment]
You're reporting CXPatcher as a malware?

**Comment by italomandara** [comment]
> I am also having this issue and using @italomandara fixes didnt seem to work. <img alt="Screenshot 2023-09-30 at 6 44 18 pm" width="765" src="https://user-images.githubusercontent.com/76608972/271768640-c9190c94-0e22-47f5-9cf0-19bdd796d31c.png"> <img alt="Screenshot 2023-09-30 at 6 44 45 pm" width="554" src="https://user-images.githubusercontent.com/76608972/271768642-332355ca-3216-41f3-aae0-7d2e4c5df5df.png">

1) try to redownload the app I tried to change the certificate to a new one that could improve things

2) you're applying xattr to the headers of D3dMetal.framework and not the app this is clearly not going to work, If you right click the app and then open is much easier.

3) in the screenshot to the right, by keeping checked "Report malware to Apple to protect other users" and clicking Move to bin you report CXPatcher to Apple as a Malware, potentially getting this app banned and throwing months of work me and @Gcenx did down the drain.

**Comment by AyAyRON123** [comment]
> > I am also having this issue and using @italomandara fixes didnt seem to work. <img alt="Screenshot 2023-09-30 at 6 44 18 pm" width="765" src="https://user-images.githubusercontent.com/76608972/271768640-c9190c94-0e22-47f5-9cf0-19bdd796d31c.png"> <img alt="Screenshot 2023-09-30 at 6 44 45 pm" width="554" src="https://user-images.githubusercontent.com/76608972/271768642-332355ca-3216-41f3-aae0-7d2e4c5df5df.png">
> 
> 1. try to redownload the app I tried to change the certificate to a new one that could improve things
> 2. you're applying xattr to the headers of D3dMetal.framework and not the app this is clearly not going to work, If you right click the app and then open is much easier.
> 3. in the screenshot to the right, by keeping checked "Report malware to Apple to protect other users" and clicking Move to bin you report CXPatcher to Apple as a Malware, potentially getting this app banned and throwing months of work me and @Gcenx (and also @stonerl @mavethee @zorikon @airsquared @andrekandore @Naicriz )  did down the drain.

I did not report it as malware as i pressed Cancel

**Comment by AyAyRON123** [comment]
It seems to be working now, sick

**Comment by serista** [comment]
Same here with 0.3.1 (which I have to use). It worked just yesterday, today it suddenly "will damage your computer".

**Comment by italomandara** [comment]
This was fixed by changing the build in the release
