### ISSUE TITLE
CrossOver 22.X + CX Patcher or CrossOver 23.5

### ISSUE THREAD

**Issue by iMonZ** [italomandara/CXPatcher#136]
What advantages does CXpatcher have if the 23.5 version has the GPT already included?

**Comment by italomandara** [comment]
it can run some games that crossover 23.5 can't run (yet) for example resident evil 7.

**Comment by italomandara** [comment]
Also i forgot to mention that are some UE4 games that can only run with dxvk enabled but 23.5 isn't able to run ue4 games through dxvk at the moment (e.g.: ace combat 7)

**Comment by italomandara** [comment]
at some point crossover will improve so much so, that CXPatcher will be discontinued, but it's still not the case.
It's already great and there are few games that run only on cx23.5  (e.g: demon slayer)

**Comment by italomandara** [comment]
closing this for not being a bug if you have further questions please use https://github.com/italomandara/CXPatcher/discussions
