### ISSUE TITLE
CS2 freezes once per match

### ISSUE THREAD

**Issue by 0xR32** [italomandara/CXPatcher#148]
I have a M1 Pro 2021 ,16GB ram and the game runs smoothly (~70 fps). However, the game freezes once per match. All I have to do is to restart everything and after that I can play pretty much until the end of the match without any freezes. It's a bit annoying to do that for every match.

Is there a setting or solution to this problem?

**Comment by italomandara** [comment]
What version of CXPatcher are you using?

**Comment by italomandara** [comment]
It can be anything I haven't debugged that, TBH crashes arent happening anymore, but you can enable the logs and post them here. also try a new bottle because sometimes reusing a bottle created with other versions of cxpatcher would cause any kind of issue.

**Comment by italomandara** [comment]
Are you using dxvk or d3dmetal?

**Comment by agent-carl** [comment]
dxvk

**Comment by Jaco6Z** [comment]
This is happening to me as well. The game freezes exactly once per match and doesn't freeze again until the next match. Crossover 23.6 patched with CXPatcher 0.4.7. I only patched DXVK and D3DMetal, since MoltenVK seems to cause the foliage to flicker.

**Comment by italomandara** [comment]
> This is happening to me as well. The game freezes exactly once per match and doesn't freeze again until the next match. Crossover 23.6 patched with CXPatcher 0.4.7. I only patched DXVK and D3DMetal, since MoltenVK seems to cause the foliage to flicker.

you can patch moltenvk and then disable fast math in the CXPatcher options to fix the foliage issue

**Comment by italomandara** [comment]
> disable fast math

Does it freeze without CXPatcher?

**Comment by Jaco6Z** [comment]
> > disable fast math
> 
> Does it freeze without CXPatcher?

yes. It freezes no matter what.

**Comment by italomandara** [comment]
> > > disable fast math
> > 
> > 
> > Does it freeze without CXPatcher?
> 
> yes. It freezes no matter what.

Then I don't think I can do much, if there is a workaround I'll add it to CXPatcher but for now, I'll close the issue
