### ISSUE TITLE
What games have become playable after using CXPatcher v0.4.5

### ISSUE THREAD

**Issue by Gcenx** [italomandara/CXPatcher#149]
I’d like to put together a list of games that working only with CXPatched CrossOver-23.6.0.

**Comment by italomandara** [comment]
Can we have this in https://github.com/italomandara/CXPatcher/discussions instead ?

**Comment by italomandara** [comment]
I'll add a couple:
- Resident Evil 7
- Dying Light 2

**Comment by niccolomineo** [comment]
> I'll add a couple:
> 
> * Resident Evil 7
> * Dying Light 2

Can you confirm RE7 is still working for you on C23.7 + CX 0.4.8? 'Cause RE3 is not, anymore...

**Comment by italomandara** [comment]
> > I'll add a couple:
> > 
> > * Resident Evil 7
> > * Dying Light 2
> 
> Can you confirm RE7 is still working for you on C23.7 + CX 0.4.8? 'Cause RE3 is not, anymore...

Yes tested today

**Comment by niccolomineo** [comment]
> > > I'll add a couple:
> > > 
> > > * Resident Evil 7
> > > * Dying Light 2
> > 
> > 
> > Can you confirm RE7 is still working for you on C23.7 + CX 0.4.8? 'Cause RE3 is not, anymore...
> 
> Yes tested today RE7 needs the full Gstreamer installation tho

Yes, GStreamer not the problem. it's the DX12 renderer erroring out.

**Comment by italomandara** [comment]
@Gcenx Moving this to discussions, people don't contribute anyway.
