### ISSUE TITLE
texture flickering CX23.6/CXP 0.4.5

### ISSUE THREAD

**Issue by Mfarshore** [italomandara/CXPatcher#150]
I have a game, Retreat to Enen and the Paradise update, running under CX22.1.1 and CXP 0.2.3. No texture flickering but some shader compilation problems which I fixed by modifying Engine.ini. Now, using CX23 and CXP 0.4.5 the games run but show definite texture flickering that looks like some sort of texture contention as the texture flashes black then correct. Loading is vastly improved and shader recompilation is no problem at all, even without the UE4 mods to Engine.ini.

I have tried patching MoltenVK and DXVK individually and both together with no luck. I have also tried substituting the original libMoltenVK.dylib that solved the UE4 black screen problem, also without success.

Is there anyway to do a dylib substitution or an Engine.ini edit to get CX23/CXP 0.4.5 back to the way CX22.1.1/CXP 0.2.3
treated shaders? I would definitely like to retain the loading and execution speed of the former and still have the way the latter handles shaders.

iMac 27" 2017 24 BG @2400 MHz; Radeon Pro 580 8 GB
Ventura 13.5

**Comment by italomandara** [comment]
There's an option in the patcher to disable fast math, try that, but the penalty is lower framerate. 
That's your temporary solution.

There's a new feature waiting to be merged in MVK that will be available hopefully in the next CXPatcher release that fixes this issue.

**Comment by Mfarshore** [comment]
And your suggestion was a winner. I can deal with the frame rate. It's a walking simulator so I can just walk slower.
Looking forward to the next release.
