### ISSUE TITLE
Upside-down & back-to-front UI components

### ISSUE THREAD

**Issue by jonwilts** [italomandara/CXPatcher#153]
After patching Crossover (23.6) with CXPatcher (0.4.5), some games seem to have upside down and/or reversed UI. Reverting to an unpatched Crossover allows the UI to appear correctly again.

This doesn't affect all games, and doesn't affect all aspects of the UI. I've experienced it with Battlefield V and TT Isle of Man 3.

A couple of screenshots: 

![Screenshot 2023-11-12 at 10 55 33 AM](https://github.com/italomandara/CXPatcher/assets/9073828/eadd8efb-1b91-4237-ad60-582d9edc2020)

This is the main game menu of TT Isle of Man 3. Note that when on this screen, mouse movement is also reversed (move the mouse left, cursor moves right, etc).

![Screenshot 2023-11-12 at 10 55 47 AM](https://github.com/italomandara/CXPatcher/assets/9073828/220e4cec-bfa1-4c83-84cf-1588f52eb8c8)

This is in game. Note that the HUD and map are upside down, but the main bike & road are the right way up.

I don't have screenshots of Battlefield V, but it was very similar - menus and on screen writing were upside down and back to front, but main game visuals were correct.

I only recently started using CXPatcher, so unclear if this is a recent regression.

**Comment by Mfarshore** [comment]
Similar problem in Bokida - Heartfelt Reunion using CX23.6/CXP0.4.5 but only for the intro. Gameplay has no HUD and seems unaffected. Also no problems with the menus.
![Screenshot 2023-11-12 at 9 10 30 AM](https://github.com/italomandara/CXPatcher/assets/134976176/a3252077-08f2-4676-9e79-02844eb219e1)
![Screenshot 2023-11-12 at 9 10 36 AM](https://github.com/italomandara/CXPatcher/assets/134976176/7e8dc743-6038-4e19-9cb4-77e0958c6b5a)

**Comment by italomandara** [comment]
this is a bug in MoltenVK I'm waiting for them to fix it

**Comment by italomandara** [comment]
@jonwilts can you please repatch with the latest release (V0.4.7) and retry? please close the issue if it's fixed

**Comment by jonwilts** [comment]
Yes - that looks like it's totally fixed. Excellent. Thank you!
