### ISSUE TITLE
CS2 getting stuck

### ISSUE THREAD

**Issue by agent-carl** [italomandara/CXPatcher#154]
> I have a problem with cs2 getting stuck after 7-10 minutes of gameplay.
> the game just stops and doesn't react to anything.

> I used the crossover with the patch from CXpatcher, then tried the clean version of the crossover but the problem remained

> CXpatcher 4.7
> Crossover 23.6

**Comment by italomandara** [comment]
closing this issue as a duplicate of https://github.com/italomandara/CXPatcher/issues/148
