### ISSUE TITLE
dxvk/esync buttons unactive, can't run programmes in the Crossover

### ISSUE THREAD

**Issue by agent-carl** [italomandara/CXPatcher#156]
I have the dxvk/esync buttons unactive, and they can't be enabled. 
i also can't run any of the programmes installed in the crossover.
>Crossover 23.6
>CXPatcher 4.7
<img width="1512" alt="Снимок экрана 2023-11-17 в 17 06 04" src="https://github.com/italomandara/CXPatcher/assets/57443863/fc72dd81-f18e-4208-ab23-e2299362b69d">

**Comment by italomandara** [comment]
Start by patching a fresh copy of crossover, then if it doesn't fix it, make a new bottle from scratch, then if it both doesn't work. we have a problem, this never happened so my question is, did you manually change something in the crossover app after or before patching?
