### ISSUE TITLE
The ground is too dark in Battlefield 1

### ISSUE THREAD

**Issue by Coulin9** [italomandara/CXPatcher#157]
As you can see, the ground is totally dark when it's foggy, and it won't turn normal even when the fog disperses .
![截屏2023-11-20 22 58 12](https://github.com/italomandara/CXPatcher/assets/114336162/4c347426-1545-4609-8cb4-02299f584537)

**Comment by italomandara** [comment]
This is a GPTK/D3dMetal issue, and it's closed source so can't fix that, will need to wait for the next release of gptk and hopefully will be released
