### ISSUE TITLE
Grand Theft Auto 3 and Vice City Definitive Edition are too dark

### ISSUE THREAD

**Issue by Jepl4r** [italomandara/CXPatcher#16]
I tried changing the brightness and contrast from the video settings and the game remains the same. Didn't test San Andreas but I think it would have the same problem.

![Screenshot 2023-05-13 alle 21 36 54](https://github.com/italomandara/CXPatcher/assets/115885800/0d993c2c-b914-4a2b-a7a0-faac931fe0c6)
![Screenshot 2023-05-13 alle 21 41 14](https://github.com/italomandara/CXPatcher/assets/115885800/48fa29a0-86c9-46a8-9d5d-3e4ce767b389)

**Comment by italomandara** [comment]
Try this in your bottle config file add at the bottom:
`"NAS_TONEMAP_C"="0"`

The file you need to modify is located in the bottle folder and is named `cxbottle.conf`
this is a temporary solution that will disable tone mapping in all ue4 games.
So if this fixes it please provide the .exe file names so that I can add the override at the next release.

**Comment by Jepl4r** [comment]
Now the games have like a grey color to them (I know that that's because the tone map is disabled).
The fact is that now all the tree textures flicker black.
Anyway here's the EXE names SanAndreas.exe ViceCity.exe and LibertyCity.exe

**Comment by italomandara** [comment]
> Now the games have like a grey color to them (I know that that's because the tone map is disabled).
> The fact is that now all the tree textures flicker black.
> Anyway here's the EXE names SanAndreas.exe ViceCity.exe and LibertyCity.exe

I'll have that fixed next release.
meanwhile try those three (the first replaces the first one i gave you):
`"NAS_TONEMAP_C"="clamp({inputColor} * float3x3( 0.2126 + 0.7874 * 1.5, 0.7152 - 0.7152 * 1.5, 0.0722 - 0.0722 * 1.5, 0.2126 - 0.2126 * 1.5, 0.7152 + 0.2848 * 1.5, 0.0722 - 0.0722 * 1.5, 0.2126 - 0.2126 * 1.5, 0.7152 - 0.7152 * 1.5, 0.0722 + 0.9278 * 1.5 ) * 1.5, 0.0, 1.0)"`
`"CXPATCHER_SKIP_NTDLLHACKS"="1"`
`"MVK_CONFIG_FAST_MATH_ENABLED"="0"`
Thanks for helping improving the patcher.

**Comment by Jepl4r** [comment]
Now it works as intended. Anyway I used all three at the same time, don't know if I was supposed to.

![Screenshot 2023-05-14 alle 00 58 27](https://github.com/italomandara/CXPatcher/assets/115885800/9a9f6bea-cc09-4b79-a00b-0e0c3425bca6)
