### ISSUE TITLE
CX 23.7

### ISSUE THREAD

**Issue by unknownsolo** [italomandara/CXPatcher#160]
CX 23.7 came out today. Not rushing anyone or anything, just wondering when should we expect an update for CXPatcher?

**Comment by rl-pavel** [comment]
Would the current CXPatcher not work with 23.7? Also, what does CXPatcher provide over what's currently bundled with CrossOver?

**Comment by unknownsolo** [comment]
wohoo! cmon @italomandara, we're counting on you :) 

(I'm happy to contribute financially to CXPatcher's development)

**Comment by italomandara** [comment]
I'll try my best to release ASAP, there's some legacy stuff I need to weed out and add the latest MoltenVK, also update the library manifests. And I can only start when I come back from the office.

**Comment by italomandara** [comment]
> wohoo! cmon @italomandara, we're counting on you :)
> 
> (I'm happy to contribute financially to CXPatcher's development)

Thanks, no need to CXPatcher is free and always will be, but feel free to ask @Gcenx how to support his work which is a very important contribution to this project.

**Comment by niccolomineo** [comment]
Hey guys thanks for what you do. I wouldn't be able to play a few games if it wasn't for your efforts. 🙏

**Comment by DuckDuckG0053** [comment]
Hello guys, i can see the repository was updated a couple minutes ago, regarding MoltenVK stuff. Is the update ready to go?

**Comment by unknownsolo** [comment]
Yes. It looks like 0.4.8 is out :) Thank you all for the quick turnaround. 

<3 CXPatcher!

**Comment by niccolomineo** [comment]
Woah, that was quick :)
