### ISSUE TITLE
Dreaded status bug

### ISSUE THREAD

**Issue by Mfarshore** [italomandara/CXPatcher#168]
Tried CrossOver 23.7/cxpatcher V0.4.9 this morning and got the Istatus assertion failure. No problems with CX 23.7/CXP 0.4.8
Tried repatch/upgrade of CX 23.7/CXP 0.4.8 and a fresh CX 23.7 with a virgin test bottle the CXP. Both approaches got the Istatus failure. See attached screenshot.

iMac 27" 2017 24 BG [@2400](https://github.com/2400) MHz; Radeon Pro 580 8 GB
Ventura 13.5
<img width="357" alt="Screenshot 2023-12-02 at 10 05 12 AM" src="https://github.com/italomandara/CXPatcher/assets/134976176/da90ec8e-bafd-4715-b262-59e7fbd7e77d">

**Comment by italomandara** [comment]
Try to upgrade with CXPatcher 0.4.9

**Comment by Mfarshore** [comment]
fixed  V0.4.10 For Crossover 23.7
