### ISSUE TITLE
Stray not working

### ISSUE THREAD

**Issue by johngriffin1** [italomandara/CXPatcher#17]
Hi, I am on an M1 Pro Macbook with Crossover Version 22.1.1 (22.1.1.35679).
I drag the app and toggle the DXVK switch on and off, but when I go to play the game Stray, most of the textures appear black and the ones that do work just flicker. I know many other people have been able to get this game to work so am I doing something wrong? I even completely uninstalled and reinstalled Crossover. It did have to update today if that helps. Any help is appreciated, thanks!

**Comment by italomandara** [comment]
Hi I just tried just in case with a fresh crossover installation, the latest patcher and my copy of stray from steam. It works, it may be something on your side. Try this: if you drag and drop your crossover app again does it tell you that it's already patched?

**Comment by johngriffin1** [comment]
It tells me "your app is updated"

**Comment by johngriffin1** [comment]
I get the Patcher and one installation of Crossover

**Comment by johngriffin1** [comment]
I have tried it in a Steam bottle and a Stray bottle but I'm not sure what env variables are. Where can I find them?
Thank you so much for troubleshooting this, also.

**Comment by johngriffin1** [comment]
I was just able to get it working by enabling DXVK and Esync!

**Comment by italomandara** [comment]
I don't think it's a cx patcher app issue, maybe the instructions were confusing or you have a duplicate crossover copy somewhere.
for example, when you download crossover it asks you to move the app, when you proceed it will not move to the usual application folder but to your user folder's application folder, and maybe you have also a copy of Crossover in the main application folder? which isn't patched? I'm not sure what's going on on your computer. 
Check those videos if you can spot if you're missing some steps in the process?
https://www.youtube.com/watch?v=ufDLEa2vu5Y
or
https://www.youtube.com/watch?v=ZeGh_u0Oa0I

**Comment by johngriffin1** [comment]
I was just able to get it working by enabling DXVK and Esync!
Thank you so much for all of the help and patience

**Comment by italomandara** [comment]
Ok we can close the issue then
