### ISSUE TITLE
after updating to 4.9 games with d3dmetal stopped running

### ISSUE THREAD

**Issue by agent-carl** [italomandara/CXPatcher#170]
after updating to 4.9 games with d3dmetal stopped running. 
tried to downgrade to 4.8, but the problem remains. 
(before updating to 4.9 everything was fine) 
(games either just don't start or writes that there is no graphics device or the game has a lot of visual glitches)

**Comment by italomandara** [comment]
On every release I'm putting the same instructions when you have this kind of problem, please follow the instrucitions, and that should fix it

**Comment by agent-carl** [comment]
same
maybe it's because of the updated MoltenVK?

**Comment by agent-carl** [comment]
where I can find the changelog?

**Comment by funk4d** [comment]
same , games with d3dmetal stopped working, unless dxvd, but its bugged

**Comment by italomandara** [comment]
try 0.4.10

**Comment by italomandara** [comment]
> where I can find the changelog?

in releases you can view the diff based on commits

**Comment by agent-carl** [comment]
> try 0.4.10

thanks, it helped :)
