### ISSUE TITLE
Elden Ring can't be launched with CXPATCHER

### ISSUE THREAD

**Issue by AugustCastles** [italomandara/CXPatcher#174]
So Elden Ring launches perfectly fine with a fresh install of Crossover, not patched. 
But oddly when running it on a patched version it crashes on startup with the error:

"The program eldenring.exe has encountered a serious problem and needs to close. We are sorry for the inconvienience"
Then below:
"This can be caused by a problem in the program or a deficiancy in Wine. You may want to check https://www.codeweavers.com/compatibility for tips about running this application."
And show details does nothing.

Im on Crossover 23.7.1 and CXPATCHER V0.4.10.
Any help would be appreciated, cheers!

**Comment by italomandara** [comment]
Have you tried to follow the troubleshooting instructions in the release notes?

**Comment by AugustCastles** [comment]
Yes! I just tried to disable and re-enable some things, and the game runs fine now. Though I still have one more question for reference. It might be dumb but I'm not super inclined with Crossover. If this issue were to happen again, how would I go about making a manual bottle for a Steam game?

**Comment by italomandara** [comment]
> Yes! I just tried to disable and re-enable some things, and the game runs fine now. Though I still have one more question for reference. It might be dumb but I'm not super inclined with Crossover. If this issue were to happen again, how would I go about manually making a bottle for a Steam game?

Steam gives you the possibility to reference any location for your game library, that's what i do, I keep games in an external HD and steam is the only thing i install in the bottle so that's easy to create a new bottle with just steam installed, and there's no need to reinstall the games just reconfigure steam.

**Comment by AugustCastles** [comment]
That makes sense, thank you for the help!

**Comment by AmrutBTallur** [comment]
I am facing the same issue. Can you please tell me how you fixed it.

**Comment by AmrutBTallur** [comment]
hey, i am facing the same issue can you please help me.

**Comment by stoc4zzo4** [comment]
AugustCastles i got the same problem how did you resolve it?

**Comment by stoc4zzo4** [comment]
> Yes! I just tried to disable and re-enable some things, and the game runs fine now. Though I still have one more question for reference. It might be dumb but I'm not super inclined with Crossover. If this issue were to happen again, how would I go about manually making a bottle for a Steam game?
I got the same problem how did you resolve it?
