### ISSUE TITLE
After uninstalling CXPatcher, cannot activate Crossover again

### ISSUE THREAD

**Issue by flaxton** [italomandara/CXPatcher#177]
I removed ~/Library/Application Support/Crossover, /Applications/Crossover.app and /Applications/CXPatcher.app and the ~/CXBottles folder

Then I logged into Codeweavers and downloaded a fresh copy of Crossover.

When I try to activate it, I get:

Unlocking failed

Failed to download license file: unsupported URL

**Comment by italomandara** [comment]
Make sure you activate with an unpatched version first and only after that you patch it.
New CXPatcher makes a backup copy so you can use that copy to do the activation and then use the patched one.

**Comment by flaxton** [comment]
Unfortunately, I didn't notice the backup part and just deleted everything.

But I got it activated again.

I created a macOS VM on Parallels, and installed and activated Crossover there.

Then I copied the Crossover.app over the network to my MacBook Air.

Opened Crossover, it asked to activate again, and this time it worked.

**Comment by flaxton** [comment]
Next time I'll be more careful!
