### ISSUE TITLE
Patcher compatibility issue

### ISSUE THREAD

**Issue by Sponge-bink** [italomandara/CXPatcher#18]
Does it have to be on macOS 13 or higher for the patch to work, or it's just what CXPatcher requires?

I patched crossover using a macOS 13 machine (since CXPatcher wouldn't launch on macOS 12), it launched after right clicking and clicking open. but when I copied the .app file to a macOS 12 machine, it just wouldn't launch. 

<img width="372" alt="image" src="https://github.com/italomandara/CXPatcher/assets/33798984/57dd387d-532c-4283-a786-488121d0b0bc">

<img width="372" alt="image" src="https://github.com/italomandara/CXPatcher/assets/33798984/a8ace4be-f0e4-4ad0-8041-805d15ad3c80">

**Comment by italomandara** [comment]
It's just CXPatcher, I will update it to be backward compatible with older Mac OS versions.
I believe you have to launch the app on the target machine, so the only solution is a CXPatcher update.

**Comment by Sponge-bink** [comment]
Thank you, I managed to launch updated CrossOver with macOS 12 after remove the quarantine attribute of the .app file.
