### ISSUE TITLE
Gstreamer for unpacking?

### ISSUE THREAD

**Issue by KaGe-93** [italomandara/CXPatcher#183]
Am I correct in saying Gstreamer is needed so files in bins for instance can be unpacked correctly?
If that is the case, when I patch crossover with cxpatcher the New crossover app cannot unpack anything at all. 
They all get error messages, while the old (original) crossover app can unpack everything fine? 

Am I doing something wrong here?

**Comment by italomandara** [comment]
Not sure what you mean by unpack.
Gstreamer is needed to play videos (windows media foundation) encoded in some formats and not supported by the base version of Crossover.
A link for the GStreamer installation is provided when you don't have it installed alternatively you can install GStreamer on Mac via Brew.

**Comment by italomandara** [comment]
Gstreamer is used to decode some video codecs that are not supported
