### ISSUE TITLE
[Request] Patcher for Crossover 24

### ISSUE THREAD

**Issue by enzofrnt** [italomandara/CXPatcher#186]
Hi, did you plan to release Patcher for CrossOver 24 ?

**Comment by italomandara** [comment]
Hello, It's planned but it might take a while

**Comment by enzofrnt** [comment]
> Hello, It's planned but it might take a while

when ?

**Comment by italomandara** [comment]
I'm talking with the dev who handles the Wine part, we haven't defined a particular deadline yet.
CX24 is quite good already, so unless you have some UE4 games that run only via DXVK or games that need full Gstreamer support (RE7) I guess it isn't that urgent isn't it? if you it's the former i can provide a pre-release with UE4 support for DXVK

**Comment by macvip** [comment]
CX24's built-in Gstreamer still doesn't support mp4 video playback; performance is laggy (while fps is 60 or higher enough) when playing some games (like LEGO Bricktales) in D3DMetal mode. So now I'm using CX23.7.1 + CXPatcher, hoping CXPatcher matches CX24 soon. Thanks for your fantastic work!

**Comment by italomandara** [comment]
> CX24's built-in Gstreamer still doesn't support mp4 video playback; performance is laggy (while fps is 60 or higher enough) when playing some games (like LEGO Bricktales) in D3DMetal mode. So now I'm using CX23.7.1 + CXPatcher, hoping CXPatcher matches CX24 soon. Thanks for your fantastic work!

Gstreamer supports is thanks to @Gcenx hard work, along with the first integration with d3dmetal in the first versions.

**Comment by denysApple** [comment]
I need CXPatcher to easily connect GPTK to Crossover

**Comment by ody** [comment]
I would appreciate a release that targets Crossover 24. There are fixes in Crossover 24 that improve the Overwatch 2 interface but the graphics still have major issues that make it unplayable, right now I keep a patched 23.7.1 around just for Overwatch 2 because it doesn't have the graphics issues

**Comment by YashAggarwal27** [comment]
any date for the release yet?

**Comment by SpiritHi** [comment]
I want to thank you for the stuff you’ve done. I’m not here to ask for a timeline like many others. But I’d appreciate patcher for crossover 24. Mainly because I play overwatch & bare crossover doesn’t run it that well

**Comment by italomandara** [comment]
> I want to thank you for the stuff you’ve done. I’m not here to ask for a timeline like many others. But I’d appreciate patcher for crossover 24. Mainly because I play overwatch & bare crossover doesn’t run it that well

what's the game you're trying to run on cx24 that doesn't run without cxpatcher? I could think of a pre-release if it's not related to GStreamer.

**Comment by SpiritHi** [comment]
> > I want to thank you for the stuff you’ve done. I’m not here to ask for a timeline like many others. But I’d appreciate patcher for crossover 24. Mainly because I play overwatch & bare crossover doesn’t run it that well
> 
> what's the game you're trying to run on cx24 that doesn't run without cxpatcher? I could think of a pre-release if it's not related to GStreamer.

I mentioned overwatch. Its just overwatch

**Comment by italomandara** [comment]
> > > I want to thank you for the stuff you’ve done. I’m not here to ask for a timeline like many others. But I’d appreciate patcher for crossover 24. Mainly because I play overwatch & bare crossover doesn’t run it that well
> > 
> > 
> > what's the game you're trying to run on cx24 that doesn't run without cxpatcher? I could think of a pre-release if it's not related to GStreamer.
> 
> I mentioned overwatch. Its just overwatch

So you need the new DXVK + new MoltenVK I'll try and pre release this week

**Comment by SpiritHi** [comment]
> > > > I want to thank you for the stuff you’ve done. I’m not here to ask for a timeline like many others. But I’d appreciate patcher for crossover 24. Mainly because I play overwatch & bare crossover doesn’t run it that well
> > > 
> > > 
> > > what's the game you're trying to run on cx24 that doesn't run without cxpatcher? I could think of a pre-release if it's not related to GStreamer.
> > 
> > 
> > I mentioned overwatch. Its just overwatch
> 
> So you need the new DXVK + new MoltenVK I'll try and pre release soon-ish

Thank you 🙏🏽 I look forward to that very much

**Comment by YashAggarwal27** [comment]
can you suggest anything that would improve performance of palworld on bare cx 24. I am on Mac air m2

**Comment by Hani-11** [comment]
> > I want to thank you for the stuff you’ve done. I’m not here to ask for a timeline like many others. But I’d appreciate patcher for crossover 24. Mainly because I play overwatch & bare crossover doesn’t run it that well
> 
> what's the game you're trying to run on cx24 that doesn't run without cxpatcher? I could think of a pre-release if it's not related to GStreamer.

Would the resident evil games run with the pre release as well?
Also thank you so much for your efforts!

**Comment by italomandara** [comment]
> > > I want to thank you for the stuff you’ve done. I’m not here to ask for a timeline like many others. But I’d appreciate patcher for crossover 24. Mainly because I play overwatch & bare crossover doesn’t run it that well
> > 
> > 
> > what's the game you're trying to run on cx24 that doesn't run without cxpatcher? I could think of a pre-release if it's not related to GStreamer.
> 
> Would the resident evil games run with the pre release as well? Also thank you so much for your efforts!

That would be the missing bit that takes more time, it will be in the official release but not in the pre-release

**Comment by Yash-2704** [comment]
Can you please tell how to access the pre release when it will be available. Will it be in the releases only or in a different area?

**Comment by italomandara** [comment]
> Can you please tell how to access the pre release when it will be available. Will it be in the releases only or in a different area?

same area

**Comment by italomandara** [comment]
https://github.com/italomandara/CXPatcher/releases/tag/v0.5-pre

**Comment by SpiritHi** [comment]
> https://github.com/italomandara/CXPatcher/releases/tag/v0.5-pre

What are the best settings for overwatch? I’m getting  great performance but bad flickering

**Comment by italomandara** [comment]
> > https://github.com/italomandara/CXPatcher/releases/tag/v0.5-pre
> 
> What are the best settings for overwatch? I’m getting great performance but bad flickering

try patching with different moltenvk options and see what works better
- don't patch
- base
- latest
![Screenshot 2024-03-23 at 12 03 38](https://github.com/italomandara/CXPatcher/assets/12135454/427116d9-4d58-4ff5-9b52-80336e0bfd14)

i heard this kind of light flashing and flickering would happen only on the first run though

**Comment by SpiritHi** [comment]
> > > https://github.com/italomandara/CXPatcher/releases/tag/v0.5-pre
> > 
> > 
> > What are the best settings for overwatch? I’m getting great performance but bad flickering
> 
> try patching with different moltenvk options and see what works better
> 
> * don't patch
> * base
> * latest
>   ![Screenshot 2024-03-23 at 12 03 38](https://private-user-images.githubusercontent.com/12135454/316239521-427116d9-4d58-4ff5-9b52-80336e0bfd14.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEyNTc3NDYsIm5iZiI6MTcxMTI1NzQ0NiwicGF0aCI6Ii8xMjEzNTQ1NC8zMTYyMzk1MjEtNDI3MTE2ZDktNGQ1OC00ZmY1LTliNTItODAzMzZlMGJmZDE0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI0VDA1MTcyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmZDk4ZTIyYTFlZTc1MDU2MjQzNjU2ODFiZjU2ZWRlZGNkMTQ0YWNiN2NlNTJjZjY5MzliODk0NzRjYmQ2MmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tGLqKvHmQ8MNad41EUt57_a_1qvwzDDnCS4BoeazaNo)
> 
> i heard this kind of light flashing and flickering would happen only on the first run though

<img width="983" alt="Screenshot 2024-03-24 at 1 20 16 AM" src="https://github.com/italomandara/CXPatcher/assets/90008238/373d4acb-71bc-4ec8-bf56-8df513e38fd5">


I don't think I see the same options in settings as you do

**Comment by SpiritHi** [comment]
> @SpiritHi that’s because your looking at CrossOver not CXPatcher

Thank you. I can change settings even after crossover being patched? Or will I have to remove the patch & then repatch?

**Comment by italomandara** [comment]
> > @SpiritHi that’s because your looking at CrossOver not CXPatcher
> 
> Thank you. I can change settings even after crossover being patched? Or will I have to remove the patch & then repatch?

You can repatch the original app, every time you patch CXPatcher makes a backup of the original Crossover in the same folder

**Comment by niosz** [comment]
For RE games like 7 i think i must wait gstreamer :( 
Thank you for awersome work!

**Comment by ouravraybanerjee** [comment]
hey so i patched my crossover with the pre release and now none of my bottles are showing up. I can see them in application support but it isn't reflecting in crossover

**Comment by italomandara** [comment]
> hey so i patched my crossover with the pre release and now none of my bottles are showing up. I can see them in application support but it isn't reflecting in crossover

https://github.com/italomandara/CXPatcher?tab=readme-ov-file#new-bottle-path

**Comment by italomandara** [comment]
No that's something that needs to be fixed in D3D Metal, that is something only Apple can fix

**Comment by italomandara** [comment]
Closing this since the request has been filfilled
