### ISSUE TITLE
Unable to start any games after applying cxpatcher

### ISSUE THREAD

**Issue by Traace** [italomandara/CXPatcher#203]
Hi, after I patched crossover 24.0.3 with cxpatcher 0.5.3 I'm unable to launch any games from Steam (tested Palworld and Dark and Darker). Both games works fine in the unpatched version :)

Steps to reproduce:
Patch Crossover 24.0.3 with cxpatcher 0.5.3 using the default settings
Open Crossover and install Stream into a new bottle.
Enable D3DMetal and msync for the new bottle.
Add a external drive to wineconfig containing a steam library.
Try to launch a game, steam reports the game is open, but it never shows anything on the screen.

Check 1:
Launch unpatched Crossover_original
Launch Steam from same bottle as before
Start the game, it works

Check 2:
Manually patch Crossover_original with newest GPTK beta.
Launch Steam
Start the game, it works using newest GPTK 👍 

Both checks lead to the conclusion that this issue is related to cxpatcher itself. Because if cxpatcher is not involved, everything works.

**Comment by italomandara** [comment]
Do you get any error message? What happens if you patch but don't use an external drive?

**Comment by italomandara** [comment]
I'm closing this for the lack of feedback, and there was no interaction for a long time.
