### ISSUE TITLE
Can't restore or open original CrossOver after patch

### ISSUE THREAD

**Issue by bagadefente** [italomandara/CXPatcher#216]
I used CXPatcher 0.5.4 on CrossOver but realized I didn’t need it. Now, I’d like to revert to my original CrossOver version, mainly because I don’t want to recreate all the bottles I have.

However, there’s no “restore” option in the File menu, and when I try to open the original app, I get the error: “CrossOver_original is damaged and can’t be opened.”

How can I resolve this issue?
Alternatively, is there a way to manually transfer the bottles from the original app to the patched one?

Thanks!

**Comment by popivyurii** [comment]
same issue. lost all my games..

**Comment by italomandara** [comment]
When you patch a backup copy is created in the same folder crossover.app is, no need to restore that's your original Crossover.
