### ISSUE TITLE
latest stable release contains pre-version number

### ISSUE THREAD

**Issue by suschizu** [italomandara/CXPatcher#219]
Hello! Just a small thing I noticed:
the version number contains a -pre suffix (0.5.8-pre(1)) although it's a stable release

<img width="435" alt="Screenshot 2024-11-19 at 16 55 19" src="https://github.com/user-attachments/assets/378b39b8-8066-450c-86c3-50be20c00051">

**Comment by italomandara** [comment]
Ok it doesn't break anything, but I'll fix that
