### ISSUE TITLE
Do I have GPTK 2? 

### ISSUE THREAD

**Issue by lectricas** [italomandara/CXPatcher#220]
Hi guys. I have crossover 24.04 and I've just downloaded the last version of CXpatcher(which is V0.5.8 for CX 24.0.5).
I just want to play BlackMesa on my Mac M1 Pro 16. 
Here is an article saying I need gptk 2 for the BlackMesa to run.
https://www.applegamingwiki.com/wiki/Black_Mesa
Do I have GPTK 2? Is GPTK2 the same as D3DMetal? 
Do I need MacOS sequoia? 
Please help.

**Comment by italomandara** [comment]
it has d3dmetal 2.0b3
which is the same shipped with GPTK2
