### ISSUE TITLE
Crossover doesn't open any app

### ISSUE THREAD

**Issue by doctorstrange99992** [italomandara/CXPatcher#221]
I don't know if it is from CXPatcher but when I try to open any spp, it does not launch but when I use Parallels it launches. Crossover gives better performance that's why I prefer it

**Comment by doctorstrange99992** [comment]
[Bug fir winebacktrace.txt](https://github.com/user-attachments/files/18203415/Bug.fir.winebacktrace.txt)

This is the log file

**Comment by italomandara** [comment]
Please don't add issues in the bug tracker if you haven't tested on unpatched crossover first

**Comment by doctorstrange99992** [comment]
> Please don't add issues in the bug tracker if you haven't tested on unpatched crossover first

I tested it with unpatched crossover but still had the same problem, what I did was reinstall crossover again which meant I needed to delete all bottles and install all apps again
