### ISSUE TITLE
Miscolored waters in Skyrim SE

### ISSUE THREAD

**Issue by Dellaster** [italomandara/CXPatcher#28]
Hi, thanks for your efforts. It seems well with Skyrim SE/AE *except* for bright green or red shaded waters. Example:
![image](https://github.com/italomandara/CXPatcher/assets/80631767/a98ba380-bf8c-4bc8-955e-cc03cf941c8b)

**Comment by italomandara** [comment]
> Hi, thanks for your efforts. It seems well with Skyrim SE/AE _except_ for bright green or red shaded waters. Example:
> ![image](https://user-images.githubusercontent.com/80631767/241108972-a98ba380-bf8c-4bc8-955e-cc03cf941c8b.png)

does it work without cxpatcher?

**Comment by italomandara** [comment]
> Bingo! Everything looks correct now. I checked several different areas/waters to be sure. Great job, thanks!

I'll try to bring this to the next release, so keep the issue open please
meanwhile you'll have to switch this variable on an off depending if you're playing a ue4 game or not

**Comment by Dellaster** [comment]
Got it. Thanks again.

**Comment by Dellaster** [comment]
> Also i see you opened an issue on the Moltenvk repo, please close that.

Hm, not that I’m aware of. I don’t recall opening any other issues and my issues menu only shows this one, either open or closed.

**Comment by italomandara** [comment]
> > Also i see you opened an issue on the Moltenvk repo, please close that.
> 
> Hm, not that I’m aware of. I don’t recall opening any other issues and my issues menu only shows this one, either open or closed.

Sorry my bad.

**Comment by italomandara** [comment]
> Got it. Thanks again.

one last thing, to have this fix in the next release I need the game folder path + exe please.

**Comment by Dellaster** [comment]
> one last thing, to have this fixed in the next release I need the game folder path + exe please.

I use custom install locations, if it matters.

Steam: drive_c\Games\Steam\steamapps\common\Skyrim Special Edition\SkyrimSELauncher.exe
GOG: drive_c\GOG Games\SSE-GOG\SkyrimSELauncher.exe

Though, as most do, I launch through skse64_loader.exe

Let me know if more info is needed.

**Comment by italomandara** [comment]
> skse64_loader.exe

Thanks that's the one I'll use.
