### ISSUE TITLE
any fix for overwatch 2?

### ISSUE THREAD

**Issue by sawawas** [italomandara/CXPatcher#31]
dont really know what to say, it takes multiple attempts for the shader cache to build since the game decides it doesn't want you to login so you have to relaunch and wait again, menu items like settings are missing, glitches everywhere and small things like not being able to see chat

so many talk about how it's playable and that's cool but is anything actually being done? do i just wait for new versions and hope it does something?

**Comment by italomandara** [comment]
I'm still waiting for MoltenVK to implement the missing features AKA transform feedback.

**Comment by italomandara** [comment]
> > I'm still waiting for MoltenVK to implement the missing features AKA transform feedback.
> 
> no idea what that means uh is that good or bad

It's kind of bad we'll have either to wait MoltenVK team to fix that (not their priority ATM) 
https://github.com/KhronosGroup/MoltenVK/issues/1869
https://github.com/KhronosGroup/MoltenVK/issues/1588

**Comment by sawawas** [comment]
i see well atleast there’s hope and im able to check what’s going on, thank you

**Comment by zaptrem** [comment]
To be clear, does this mean OW2 is currently unplayable with MetalD3D as well as MoltenVK?

**Comment by sawawas** [comment]
> To be clear, does this mean OW2 is currently unplayable with MetalD3D as well as MoltenVK?

no many 2d elements are broken and the biggest thing is settings, theres a way to edit a file with some settings and an app to do it but alot are missing

**Comment by Gcenx** [comment]
The issues with OverWatch2 are Metal bugs, the game runs properly with DXVK enabled on macOS Sonoma, you’ll need to skip “external resources” option as D3DMetals DXGI dll prevents the game for running.

**Comment by Devolla** [comment]
it SAYS I need windows 10 for whatever reason

**Comment by Gcenx** [comment]
> it SAYS I need windows 10 for whatever reason

If that was a Win10 bottle yes it seems to be incorrectly reporting itself as Win8.1 I’ve resolved this locally. It’ll be resolved in a future CXPatcher release.

**Comment by italomandara** [comment]
closing this for not being a CXPatcher bug if you have further questions please use https://github.com/italomandara/CXPatcher/discussions
