### ISSUE TITLE
"Drag your crossover app here" not showing

### ISSUE THREAD

**Issue by OllumHD** [italomandara/CXPatcher#39]
Hello,
I wanted to patch my crossover as i'm on sonoma, but I found out that I cant.

For reference this is what i'm seeing:
<img width="512" alt="Screenshot 2023-06-23 at 22 42 21" src="https://github.com/italomandara/CXPatcher/assets/66539176/47631f87-4dd0-4336-b3bb-a1ced7e5859f">

And this is what someone else sees (i found this on a youtube video)
<img width="283" alt="Screenshot 2023-06-23 at 22 45 54" src="https://github.com/italomandara/CXPatcher/assets/66539176/eeeb9b46-0689-4248-97d3-d551737ebee1">

Im using the current version 0.2.14

**Comment by OllumHD** [comment]
Update: im using the prerelease and it worked perfectly

**Comment by italomandara** [comment]
This is the new sonoma gptk integration you need to provide gptk dmg drive from “load external library” otherwise you’ll have to ise the pre-release version for now

**Comment by italomandara** [comment]
fixed in #41
