### ISSUE TITLE
V0.2.15 and external resources

### ISSUE THREAD

**Issue by MysticalOS** [italomandara/CXPatcher#43]
I can't find any evidence external resources actually works what so ever. The patched version of application is identical whether it's enabled or disabled. and no dx12 games work following instructions to letter.

It doesn't copy the required framework anywhere into binary
it doesn't copy the modified d3d to metal libs to binary even when you select the porting kit disk before doing so. Far as i can tell it's same as if external option was not selected.

**Comment by MysticalOS** [comment]
Just to add, I copied the files manually after using patcher and it works fine. so for some reason, despite selecting the mounted disk image for porting kit, it didn't actually auto copy any files.

successfully playing diablo 4 in crossover directly, using patcher and manually copying files that didn't copy over though.

**Comment by italomandara** [comment]
Please make sure you followed the steps correctly, try the instructions here: https://www.youtube.com/watch?v=VVwX-cMKUPk.
There must be something that happened during the steps, maybe you didn't select the drive correctly? perhaps you selected the folder instead of the volume?

**Comment by MysticalOS** [comment]
I followed it to the letter. I even used that video as a guide. I selected the volume, did patching, it didn't copy any files at all from the volume. not a one. is it possible the volume name mismatches based on WHEN you downloaded it? I couldn't find the script in source code to determine what it's actually looking for to find out.

**Comment by MysticalOS** [comment]
Did more testing, it's copying some of the files, just not the actual "lib/external*" folder and framework therein. it did copy libs/wine/* contents over, but the libs/external folder was not, and without that it doesn't fully work.

**Comment by italomandara** [comment]
> I followed it to the letter. I even used that video as a guide. I selected the volume, did patching, it didn't copy any files at all from the volume. not a one. is it possible the volume name mismatches based on WHEN you downloaded it? I couldn't find the script in source code to determine what it's actually looking for to find out.

The volume name is the one you select the only fixed path is /lib/ I’ll re-download gptk dmg and try again, but this is the first time i hear of this issue, it seems to work for everyone else maybe it’s a permission issue, but you should be prompted with the auth

**Comment by italomandara** [comment]
Ill see if i can add logfiles tonights so that we have something to investigate. what’s happening is really weird

**Comment by ryantrip** [comment]
I'm running into the same issue, let me know if there's anything I can provide. Should the "External" folder be placed within "Lib" under CrossOver like this?
<img width="177" alt="image" src="https://github.com/italomandara/CXPatcher/assets/24561062/20f415b0-e77c-4e99-87b5-55802fa1a1af">

**Comment by italomandara** [comment]
> I'm running into the same issue, let me know if there's anything I can provide. Should the "External" folder be placed within "Lib" under CrossOver like this?
> <img alt="image" width="177" src="https://user-images.githubusercontent.com/24561062/248586313-20f415b0-e77c-4e99-87b5-55802fa1a1af.png">

yes that's where it should be copied

**Comment by ryantrip** [comment]
Thank you, I was able to resolve the issue by copying all the files together manually and merging them with the existing files behind CrossOver.

**Comment by MysticalOS** [comment]
Yeah I just encountered another user on gaming discord that had same problem

**Comment by italomandara** [comment]
I'll add a logging option in the next release so that we can investigate this better

**Comment by italomandara** [comment]
I removed 0.2.15 since it needs some investigation, V0.2.14 should work as usual

**Comment by italomandara** [comment]
@MysticalOS @ryantrip thanks for reporting this,  I've opened a PR to fix the issue if you want to test: https://github.com/italomandara/CXPatcher/pull/47

**Comment by italomandara** [comment]
the fix has been tested and now works
