### ISSUE TITLE
A lot of errors keep popping up when trying to install steam or any other game

### ISSUE THREAD

**Issue by Dhruv-1729** [italomandara/CXPatcher#46]
For more information, I following this tutorial: https://www.youtube.com/watch?v=VVwX-cMKUPk

https://github.com/italomandara/CXPatcher/assets/129688441/7793ae1b-b006-4002-8b40-5d226d72d546

MacOs Sonoma 14.0 Beta Macbook Pro M1 2021

**Comment by italomandara** [comment]
The app is unpatched, there have been reports for that and I'm investigating...

**Comment by Dhruv-1729** [comment]
What do you mean?

**Comment by italomandara** [comment]
> What do you mean?

What are the steps you followed when you used cxpatcher? I'm trying to figure out what causes this.

**Comment by italomandara** [comment]
V0.2.15 has been removed try with V0.2.14

**Comment by sawawas** [comment]
after updating steam like where they changed the ui it logged me out and the login screen (steamwebhelper) is blank so i thought to just reinstall and followed that video but it's saying "“CrossOver” is damaged and can’t be opened. You should move it to the Bin." ???

**Comment by sawawas** [comment]
doing xattr -cr /Applications/CrossOver.app is giving 
xattr: No such file: /Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib/external/D3DMetal.framework/Headers

**Comment by sawawas** [comment]
im bored and opening it for 10 minutes worked im sorry ive always been an error magnet but no games work anymore, porting toolkit lets them open and crash and dsvk they dont open but an invisible crash window opens

**Comment by italomandara** [comment]
> previously i was using https://www.youtube.com/watch?v=5NQQCR74FQE for every game and today after updating steam like where they changed the ui it logged me out and the login screen (steamwebhelper) is blank so i thought to just reinstall and followed that video but it's saying "“CrossOver” is damaged and can’t be opened. You should move it to the Bin." ???

If you read the instructions, you'll find out that you need to open your fresh copy of Crossover at least once before patching

**Comment by sawawas** [comment]
i did

**Comment by italomandara** [comment]
This is strange I'm working on a logger functionality that would help investigate what went wrong in the patching process, without further info idk what it could be. It works for me and I've been playing with patched crossover for some time...

**Comment by sawawas** [comment]
you know what idek whats happening anymore the game is working with dxvk off and im tired of this

**Comment by italomandara** [comment]
> What do you mean?

If you haven't used cxpatcher and this is just a generic question for crossover I'll have to close this issue.
