### ISSUE TITLE
Elden Ring somehow doesn't work with CXPatcher integrated with newer GPTK beta 1.02. 

### ISSUE THREAD

**Issue by serista** [italomandara/CXPatcher#49]
Subj. 

Works fine if integrated with initial version of GPTK.  Game doesn't start and WINE shows error window, unable to retrieve detailed information. Tested on Ventura / CrossOver 22.1.1.

**Comment by Gcenx** [comment]
CXPatcher hasn’t been updated to support D3DMetal-1.0.2 yet, you’ll lightly need go wait for the next release

**Comment by italomandara** [comment]
> Subj.
> 
> Works fine if integrated with initial version of GPTK. Game doesn't start and WINE shows error window, unable to retrieve detailed information. Tested on Ventura / CrossOver 22.1.1.

It's important to note that GPTK isn't fully supported on Ventura for it uses new Metal extensions. You'd better start using Sonoma instead even if this might not be thae actual issue...

**Comment by serista** [comment]
> It's important to note that GPTK isn't fully supported on Ventura for it uses new Metal extensions. I recommend to start using Sonoma instead even if this might not be the actual issue...

Yep, works on Sonoma.

**Comment by Gcenx** [comment]
D3DMetal-1.0.2 now has a hard requirement of macOS Sonoma.

**Comment by italomandara** [comment]
Closing because is related to gptk on ventura which is  unsupported
