### ISSUE TITLE
[Feature Requests] Restore to defaults, status check, and Semaphore ?

### ISSUE THREAD

**Issue by vesper8** [italomandara/CXPatcher#5]
First of all thanks a ton for making this! I was really hoping someone would. It's easy enough to do things manually but it's annoying having to redo things whenever there's a new update.

Would it make sense, for future features, to add a feature for restoring your CrossOver installation to its initial defaults?

As well as a status check of sorts that shows which versions are installed /  which versions are not default?

Lastly, some games, such as Overwatch, require additional modifications.

Overwatch requires you to Enable Semaphore as detailed in this thread:

https://www.reddit.com/r/macgaming/comments/129jzv4/overwatch_2_is_now_playable_on_apple_silicon_with/

Which by the way also points to a similar project (Though yours is more versatile IMO) https://github.com/Marqasa/overwatch-crossover-patch

Other flags may need to be modified in the future so having the means of having some kind of UI for making modifications to ~/Library/Application Support/CrossOver/Bottles/**bottle_name**/cxbottle.conf would be great and future proof rather then specifically targeting one flag in that file.

Great work in any case!!! Big thanks!

**Comment by italomandara** [comment]
Sure, I was actually thinking about things about restore, upgrade (patching an already patched version with a new release) among the other things, I'll check the requirements and add those settings for OW. thanks for the suggestions!

**Comment by italomandara** [comment]
@vesper8  As promised: Restore functionality and support for Overwatch (it was already there!)
https://github.com/italomandara/CXPatcher/pull/7

**Comment by italomandara** [comment]
@vesper8  As promised: Restore functionality and support for Overwatch (it was already there!)
https://github.com/italomandara/CXPatcher/pull/7

**Comment by italomandara** [comment]
@vesper8  As promised: Restore functionality and support for Overwatch (it was already there!)
https://github.com/italomandara/CXPatcher/pull/7

**Comment by vesper8** [comment]
@italomandara Thanks for this update : )

It would be great however if the app could display the versions of the currently installed DXVK/Molten-VK. Also when attempting to patch an already patched CrossOver, it should be able to patch it with the latest versions anyway.. currently it just says "this version is already patched". So if I want the latest patch, I have to first delete the CrossOver app, reinstall it, and then patch it again.

It's also not clear what the "patch any version" does.

And if there's a way to restore defaults.. it's also not clear how to do that.

**Comment by italomandara** [comment]
> @italomandara Thanks for this update : )
> 
> It would be great however if the app could display the versions of the currently installed DXVK/Molten-VK. Also when attempting to patch an already patched CrossOver, it should be able to patch it with the latest versions anyway.. currently it just says "this version is already patched". So if I want the latest patch, I have to first delete the CrossOver app, reinstall it, and then patch it again.
> 
> It's also not clear what the "patch any version" does.
> 
> And if there's a way to restore defaults.. it's also not clear how to do that.

I think you missed some releases.
You don't have to redownload or reinstall.
You can "Repatch" an already patched app by simply restoring it, by going to the `file -> restore` menu (https://github.com/italomandara/CXPatcher/releases/tag/V0.2.7) and then drag and drop again.
I'm already working on "Repatching" automatically but I've been tangled with other issues with DXVK which have a bigger priority, but it's in my to-do list.

**Comment by vesper8** [comment]
Ah cool. I did try all of your latest releases but maybe I missed the part where you explained the restore button was in the file menu. Just my opinion but I think those functionalities should be exposed in the main UI itself rather than "hidden" under the file menu. You've got lots of room in the UI after all. Would be nice to have details such as version numbers for MoltenVK / DXVK.. like a before -> after numbers. Just nitpicking though, what matters most is that it works and I do appreciate that you keep making it better!
