### ISSUE TITLE
After patching CrossOver with CXPatcher integrated with GPTK, DXVK games that used to work don't run anymore.

### ISSUE THREAD

**Issue by serista** [italomandara/CXPatcher#51]
CrossOver 22.1.1 / CXPatcher 0.2.15 / GPTK beta 1.0 integrated / Ventura

Before GPTK integration, Stray and NieR Replicant worked fine through DXVK (don't have other games installed) on CXPatched CrossOver. Now they refuse to run through DXVK. I thought that GPTK shouldn't affect DXVK in any way? Turns out it messes with it somehow.

It's not too convenient to repatch CrossOver with or without GPTK to play different games )

**Comment by italomandara** [comment]
This is a known issue and it's under investigation, it isn't easy to find a viable solution, meanwhile, you can have two copies of crossover. Also don't use GPTK on Ventura it really isn't worth it.

**Comment by serista** [comment]
> Also don't use GPTK on Ventura it really isn't worth it.

Not in my case )  I tested Elden Ring on Mac MIni M1 8GB and it worked fine, also compared how it run on Ventura and Sonoma - Metal HUD showed the same FPS, there were almost no stutters or hiccups in both cases. I posted screen captures in r/macgaming on Reddit.

**Comment by Gcenx** [comment]
The official requirements for D3DMetal is macOS Sonoma and as of [Game_porting_toolkit_beta_1.02.dmg](https://download.developer.apple.com/Developer_Tools/Game_porting_toolkit_beta_1.0.2/Game_porting_toolkit_beta_1.02.dmg) that’s now a hard requirement.

Honestly allowing installation below macOS Sonoma will just lead to more issues being opened.

**Comment by MysticalOS** [comment]
Yeah either swtich back to hard require sonoma (only if using external resources), or emphasize to user that they need to use 1.0 on ventura..

I woudln't lock ENTIRE program behind sonoma though since obviously it's still a good patcher for dxvk/moltenvk for ventura when not using GPTk.

**Comment by italomandara** [comment]
> Yeah either swtich back to hard require sonoma (only if using external resources), or emphasize to user that they need to use 1.0 on ventura..
> 
> I woudln't lock ENTIRE program behind sonoma though since obviously it's still a good patcher for dxvk/moltenvk for ventura when not using GPTk.

I was thinking I'll just grey out the GPTK option on Ventura

**Comment by Gcenx** [comment]
Not the entire program just the D3DMetal installation since it’s official requirement has always been macOS Sonoma.

**Comment by serista** [comment]
> I was thinking I'll just grey out the GPTK option on Ventura

But it works great with 1.0 on Ventura, why to remove the possibility.

**Comment by Gcenx** [comment]
> > I was thinking I'll just grey out the GPTK option on Ventura
> 
> But it works great with 1.0 on Ventura, why to remove the possibility.

Nothing is stopping you from use an older version of CXPatcher or running ditto command yourself against `Game_porting_toolkit_beta.dmg`

**Comment by Jayian1890** [comment]
I'm running into this same issue, but i'm on sonoma. Without GPTK games work, with it, nothing runs.

**Comment by MysticalOS** [comment]
especially with 32 bit apps. DXVK is king for older apps. I don't even use two diff crossovers, just two diff bottles, the DXVK bottle and D3DMetal one.

**Comment by italomandara** [comment]
Closing because is related to gptk on ventura which is unsupported
