### ISSUE TITLE
Move game from GPTK to CrossOver + CXPatcher

### ISSUE THREAD

**Issue by kaldown** [italomandara/CXPatcher#53]
Installed DiabloIV and played using [this](https://www.outcoldman.com/en/archive/2023/06/07/playing-diablo-4-on-macos/#install-game-porting-toolkit) guide

After that I thought it would be good idea to place each game in CrossOver.
So I installed fresh CrossOver.
Run, and instantly close one.
Patched Crossover.

- installed battle.net in CrossOver
- copied Diablo4 from another Wine environment (the one from guide at the top)
- clicked "run" Diablo4.exe and I see an error:
**This instance being hacked by CXPatcher**

Is it possible to move Whole folder between different environment (GPTK and Crossover ones) and assume it should work? (I have least amount of space and weak internet connection, that's why I'm doing it)?
Or should I download whole new instance of diablo using battlenet downloader in isolated crossover bottle from itself?

**Comment by italomandara** [comment]
This instance being hacked by CXPatcher is a normal log entry ignore that.
Just moving folders doesn't work with all games unfortunately...

**Comment by kaldown** [comment]
@italomandara thanks for letting me know. I will try to download diablo from fresh Crossover install someday to clarify.
