### ISSUE TITLE
Hitman: World of Assassination Error Message

### ISSUE THREAD

**Issue by mcjmccartney** [italomandara/CXPatcher#57]
Hi,

Tried opening up Hitman: World of Assassination and I receive the following error within CrossOver:

<img width="359" alt="Screenshot 2023-07-12 at 19 59 22" src="https://github.com/italomandara/CXPatcher/assets/78650978/81d0604a-46a1-4f10-b690-a3b0595502b5">

I'm using OS Sonoma 14.0.

Many Thanks!

**Comment by italomandara** [comment]
That's just a normal log message you can ignore that, what version of cxpatcher are you using?
