### ISSUE TITLE
Crossover 23 beta not being recognized by CX Patcher 

### ISSUE THREAD

**Issue by SeanNYU1375** [italomandara/CXPatcher#59]
Hi. I downloaded the beta right from the Codeweavers website and I am getting the following error when trying to drag/drop into CXPatcher. I know the beta just dropped but wanted to see if there was a quick workaround.
<img width="391" alt="Screenshot 2023-07-13 at 1 40 52 PM" src="https://github.com/italomandara/CXPatcher/assets/90221347/85b87cbb-29e1-4065-999d-89465ef7d587">

**Comment by mavethee** [comment]
![CleanShot 2023-07-13 at 20 57 38@2x](https://github.com/italomandara/CXPatcher/assets/47083527/2004686e-88ed-4442-887a-20dd6fc3f49b)

**Comment by SeanNYU1375** [comment]
Sorry wasn't in the discord! You can delete this, my bad I didnt see it in the release notes or readme.

**Comment by oscarbg** [comment]
Also @Gcenx shared that being wine-8.x Based D3DMetal integration it’s impossible right now..
