### ISSUE TITLE
UE4 hack with linear contrast

### ISSUE THREAD

**Issue by sofakng** [italomandara/CXPatcher#6]
The UE4 hack with linear contrast works fantastic!

Are you the author or did this come from somewhere else?

**Comment by italomandara** [comment]
I'm the author, but the main workaround of skipping/overriding LUT that made this possible is from @nastys

**Comment by sofakng** [comment]
Thanks again!  Yes, I was aware of @nastys workaround but the gray colors were distracting so I appreciate your additional workaround.

I really hope the final solution (geometry shaders) is not too far off.  I've been hoping it would be prioritized because it would fix a ton of games.

**Comment by sofakng** [comment]
One more question...

I'm using your patches with @gcenx's wineskinserver (instead of crossover).

Are your included DXVK DLLs different from @gcenx's?  (https://github.com/Gcenx/DXVK-macOS/releases, v1.10.3-20230402)

Also, what is your included ntdll.so?

Thanks again for everything!

**Comment by Gcenx** [comment]
@sofakng this is using DXVK-macOS v1.10.3-20230402

`WS11WineCX64Bit22.1.1-rc1` shipped ntdll.so unix library's already includes the fastmath/lod workaround hacks. The one in CXPatcher is more specific to CrossOver.

**Comment by sofakng** [comment]
Got it.  Thanks!  It sounds like I only need to be concerned with the new libMoltenVK.dylib file then.

Thanks so much for your hard work guys!  I saw the videos of Deep Rock Galactic working which is fantastic!

**Comment by anatoliykant** [comment]
Can **UE4 hack** help me with **video glitches** in games like **Starship Troopers Terran Command** & **Pharaoh A New Era**? 

Video screenshot from the game Starship Troopers Terran Command:
https://i.imgur.com/KfPmaz0.jpg

**Comment by italomandara** [comment]
> **Starship Troopers Terran Command** & **Pharaoh A New Era**

Only if it's a ue4 game on dx11 but it's not guaranteed for all games, also Gptk will work much better if you're on sonoma.

**Comment by anatoliykant** [comment]
**FIXED**

Yes, I'm sorry I didn't specify my environment right away.

**Env**:
- Mac OS **Sonoma** beta 14.0 (**23A5286i**)
- **CXPatcher 0.2.16**
- **gptk 1.0.2**
- **Crossover 22.1.1**

I managed to fix a glitch when playing a video in the menu before starting any mission in the game **Starship Troopers - Terran Command**
After the Crossover CXPatcher + gptk 1.0.2 patch, I opened the /Applications/CrossOver.app/Contents/SharedSupport/CrossOver/share/crossover/bottle_data/cxbottle.conf file and added
`"MVK_CONFIG_FAST_MATH_ENABLED" = "0"`
After that, the video in the game is displayed as it was intended by the developer (without shader errors and glitches).
proof - https://imgur.com/3pBsfFH

P.S. Most of the games on my steam run fine on vanilla gptk 1.0.2 + terminal (without using Crossover). But **Starship Troopers - Terran Command** won't even launch.

**Comment by anatoliykant** [comment]
**FIXED**

Yes, I'm sorry I didn't specify my environment right away.

**Env**:
- Mac OS **Sonoma** beta 14.0 (**23A5286i**)
- **CXPatcher 0.2.16**
- **gptk 1.0.2**
- **Crossover 22.1.1**

I managed to fix a glitch when playing a video in the menu before starting any mission in the game **Starship Troopers - Terran Command**
Just had to carefully re-patch Crossover with CXPatcher + gptk 1.0.2
After that, the video in the game is displayed as it was intended by the developer (without shader errors and glitches).
proof - https://imgur.com/3pBsfFH

P.S. Most of the games on my steam run fine on vanilla gptk 1.0.2 + terminal (without using Crossover). But **Starship Troopers - Terran Command** won't even launch.

**Comment by italomandara** [comment]
Sorry just doing a cleanup of non-issues in this section of the repo, thanks for the feedback
for further questions/discussions please use https://github.com/italomandara/CXPatcher/discussions
