### ISSUE TITLE
Homebrew Cask

### ISSUE THREAD

**Issue by stonerl** [italomandara/CXPatcher#68]
Just to let you know. I created a Homebrew cask for CXPatcher:

Homebrew/homebrew-cask/pull/151166

And while I was on it, one for GStreamer as well:

Homebrew/homebrew-cask/pull/151165

**Comment by italomandara** [comment]
Amazing, thanks!

**Comment by stonerl** [comment]
Hmm, the CXPatcher Cask got refused because the app is neither signed nor notarized. I assume you don't have a paid Apple Developer Account.

We can use your repo to host the cask(s). Could you create a new branch that we can use as the Homebrew Tap? It should be named `homebrew-CXPatcher`

Once you created it, I will open a PR with the Casks.

**Comment by stonerl** [comment]
Just an additional note. You can either create an empty repo and only host the Casks, or you clone your existing CXPatcher repo and sync it whenever you release a new version.

If you do the former, I think it would be a good idea to add this new repo as a sub-repo to the main repo.

But I leave this up to you.

**Comment by stonerl** [comment]
Here is the repo for Homebrew:

https://github.com/stonerl/homebrew-CXPatcher/

It is all set up. You just need to clone it.

**Comment by italomandara** [comment]
> Just an additional note. You can either create an empty repo and only host the Casks, or you clone your existing CXPatcher repo and sync it whenever you release a new version.
> 
> If you do the former, I think it would be a good idea to add this new repo as a sub-repo to the main repo.
> 
> But I leave this up to you.

Do you mean as git submodule?

**Comment by stonerl** [comment]
> > Just an additional note. You can either create an empty repo and only host the Casks, or you clone your existing CXPatcher repo and sync it whenever you release a new version.
> > If you do the former, I think it would be a good idea to add this new repo as a sub-repo to the main repo.
> > But I leave this up to you.
> 
> Do you mean a submodule?

Yes, but after some thinking, it isn't really necessary. A separate repo is just fine.

**Comment by Naicriz** [comment]
@stonerl It doesnt work yet? because i tried and it could not find the repository after been added with brew tap.

Also, thanks for this contribution, it is a save timer!

**Comment by stonerl** [comment]
Not at the moment @italomandara needs to clone the repo into his account.

**Comment by italomandara** [comment]
> Not at the moment @italomandara needs to clone the repo into his account.

I'll do as soon as i have some time for the time being i assigned you to this since you've done all the work

**Comment by stonerl** [comment]
@Naicriz You can give it a try now.

@italomandara When I find some time I'll fiddle around with GitHub Actions to automatically update the repo whenever you release a new version.

**Comment by Naicriz** [comment]
> @Naicriz You can give it a try now.
> 
> @italomandara When I find some time I'll fiddle around with GitHub Actions to automatically update the repo whenever you release a new version.

Thanks @stonerl,
I forked your repo lastnight so I could be able to use it! and works perfectly. I'll give it a try today, thanks!

**Comment by italomandara** [comment]
> BUMP_CASK_TOKEN

Done!

**Comment by stonerl** [comment]
Perfect, everything seems to work. CXPatcher updates are checked for twice a day and for GStreamer every 14 days. If an update is found, it automatically opens a pull request.
