### ISSUE TITLE
Everquest not working after patching No 3d Device found

### ISSUE THREAD

**Issue by Cytherion** [italomandara/CXPatcher#83]
After patching Everquest no longer works before patching Everquest detects that an Nvidia 8800 GT is listed as the available 3D device after patching video card list is blank and the game launcher fails saying "No 3D device found".

**Comment by Cytherion** [comment]
Yeah, I'm running other dx11 and dx12 games in Crossover so imported GPTK.  Those work.  Thought Crossover was supposed to fall back to OpenGL for dx9 games. 

I Thought maybe there was an override or something I could try without having to resort to having to separate crossovers.

**Comment by Gcenx** [comment]
Due to the awful way Apple handled D3DMetal it replaces wines builtin files with it’s custom stubs that do everything on the macOS side, this breaks any fallbacks for 64Bit games and other weird side affects.

The only way to currently handle things is having two copies of CrossOver unfortunately.

**Comment by Cytherion** [comment]
Yep, that worked I didn't even have to create a new bottle just downloaded an unpatched Crossover.  I did have to go into winecfg and set dxgi to disabled.

**Comment by italomandara** [comment]
Issue solved
