### ISSUE TITLE
Ntdll not disabling fast math for some games

### ISSUE THREAD

**Issue by KyrosWeb** [italomandara/CXPatcher#84]
Hi I'm on Ventura , M2 Pro 16Gb.
When i Patch crossover and i try to execute DBZ Kakarot (UE4) i read a "Fatal Error" alert.
If i restore Crossover everything works good (The game is unplayable but at least it starts).
Is there a solution?
Regards

**Comment by KyrosWeb** [comment]
Here is the CXlog
[Notepad++.cxlog.zip](https://github.com/italomandara/CXPatcher/files/12192548/Notepad%2B%2B.cxlog.zip)

**Comment by KyrosWeb** [comment]
He
[DBZKakarot.cxlog.zip](https://github.com/italomandara/CXPatcher/files/12192563/DBZKakarot.cxlog.zip)
re is the log

**Comment by KyrosWeb** [comment]
Some News : The [V0.2.17] works perfectly!!!!!

**Comment by italomandara** [comment]
There will be a new release with major changes that also fix this problem

**Comment by Gcenx** [comment]
Please try again with V0.2.20

**Comment by KyrosWeb** [comment]
I'll do it ASAP

**Comment by KyrosWeb** [comment]
It starts now but with black shadows. I post the screens that show how it is in v.0.2.17 and now

v.0.2.17
<img width="1512" alt="Screenshot 2023-08-01 alle 10 46 35" src="https://github.com/italomandara/CXPatcher/assets/32783932/d6903314-9960-4209-bda9-2d121c25a43a">

v.0.2.20
<img width="1512" alt="Screenshot 2023-08-01 alle 10 41 43" src="https://github.com/italomandara/CXPatcher/assets/32783932/a545b5b0-12c6-4ec2-8677-1b9f0eb50164">

@italomandara @Gcenx

**Comment by italomandara** [comment]
Are those shadows flickering? can you provide a short video?

**Comment by italomandara** [comment]
@KyrosWeb try the env variable MVK_CONFIG_FAST_MATH_ENABLED=0 or add "MVK_CONFIG_FAST_MATH_ENABLED" = "0" in your bottle configuration

**Comment by italomandara** [comment]
ok @Gcenx something went wrong with ntdll

**Comment by Gcenx** [comment]
I’ll take a look after work today

**Comment by Gcenx** [comment]
@KyrosWeb please re-patch with V0.2.21

**Comment by KyrosWeb** [comment]
I've removed "MVK_CONFIG_FAST_MATH_ENABLED" = "0" in the bottle config to be sure that everything was working fine.
It's Perfect now.
