### ISSUE TITLE
libs shipped with v0.2.18 brake some games

### ISSUE THREAD

**Issue by stonerl** [italomandara/CXPatcher#85]
I patched CrossOver with the latest CXPatcher (v0.2.18) and at least two games that were running before are now crashing on start.

- Metal: Hellsinger (Unity)
- Hellblade: Senua's Sacrifice (UE4)

#84 might be related.

**Comment by italomandara** [comment]
I own one of them Will test now

**Comment by italomandara** [comment]
@stonerl One of them works for me:

![Screenshot 2023-07-27 at 14 17 51](https://github.com/italomandara/CXPatcher/assets/12135454/ec22382e-472b-4923-b903-730f069eba93)
But I have a fresh bottle with steam installed, maybe that's why

**Comment by stonerl** [comment]
Hmm. I'll try with a fresh bottle and report back.

**Comment by stonerl** [comment]
Still crashes for me. Even when I create a new bottle. I'm running macOS 13.5 (Ventura). You're on Sonoma, aren't you?

**Comment by italomandara** [comment]
I am on Sonoma

**Comment by stonerl** [comment]
That is the error I get on my system when I start Hellblade:

![CleanShot 2023-07-27 at 15 26 26@2x](https://github.com/italomandara/CXPatcher/assets/2091312/02101751-962f-4d33-ae3d-aee6c4d7e9bd)

**Comment by italomandara** [comment]
And this works with the previous patches?

**Comment by stonerl** [comment]
> And this works with the previous patches?

Yes, if I downgrade to 0.2.17 I can run/play the games.

**Comment by stonerl** [comment]
This is the backtrace for Metal: Hellsinger crashing. Maybe @Gcenx has any use for this.

[backtrace.txt](https://github.com/italomandara/CXPatcher/files/12186010/backtrace.txt)

**Comment by Gcenx** [comment]
> This is the backtrace for Metal: Hellsinger crashing. Maybe @Gcenx has any use for this.
> 
> [backtrace.txt](https://github.com/italomandara/CXPatcher/files/12186010/backtrace.txt)

Unfortunately backtracks are mostly unless it’s need a cxlog

**Comment by stonerl** [comment]
@Gcenx Here they are:

[Hellblade Senua's Sacrifice.cxlog.txt](https://github.com/italomandara/CXPatcher/files/12186160/Hellblade.Senua.s.Sacrifice.cxlog.txt)
[Metal Hellsinger.cxlog.txt](https://github.com/italomandara/CXPatcher/files/12186161/Metal.Hellsinger.cxlog.txt)

**Comment by Gcenx** [comment]
@stonerl I'm assuming from these logs your trying to launch the games directly from CrossOver UO with the launcher icons that instead for loading them from Steam?

**Comment by stonerl** [comment]
Yes, but they also crash when I start dem from within Steam.

Do you need a cxlog für this as well?

**Comment by Gcenx** [comment]
@stonerl yes please provide a cxlog when launched from within Steam as the currently logs have no mention of loading any d3d dll meaning it doesn’t get very far.

**Comment by stonerl** [comment]
@Gcenx here are the logs when the apps are started from within Steam.

[Hellblade-Steam.cxlog.txt](https://github.com/italomandara/CXPatcher/files/12187802/Hellblade-Steam.cxlog.txt)
[Metall Hellsinger-Steam.cxlog.txt](https://github.com/italomandara/CXPatcher/files/12187804/Metall.Hellsinger-Steam.cxlog.txt)

**Comment by Gcenx** [comment]
Please try again with V0.2.20

**Comment by stonerl** [comment]
v0.2.20 fixed the issue.
