### ISSUE TITLE
I'm on macOS 12, and CXPatcher requires 13.

### ISSUE THREAD

**Issue by StupidRepo** [italomandara/CXPatcher#91]
I'm not upgrading to 13 or any higher version. Is someone gonna port this to macOS 12?

**Comment by italomandara** [comment]
Not in my current plans, I checked in the past if it was a quick win but it requires some major changes in the code, to replace the functionalities I'm using in swiftUI.
Not a priority for now. But if anyone is willing to open a PR I'm willing to review and merge.

**Comment by ultratiem** [comment]
Apple has made the base requirements for GPTK, Sonoma.

**Comment by ultratiem** [comment]
Licensing. They don't want a situation where all they do is open up emulation/virtualization. The aim here is to get developers to actually port their games over with the least amount of money possible.

I wouldn't expect any more out of the GPTK or rely on it moving forward.

**Comment by ikir83** [comment]
> 

Why you are not updating? There are so many advantages to do that. No sense to me.

**Comment by ultratiem** [comment]
There are no updates to CX 23 because Apple built GPTK against 22.1.1. Apple has to update GPTK for CXPatcher to work with CX 23. Apple likely won't bother. 

@mferrier GPTK won't run on Ventura. And it was never meant to. The fact it worked was an oversight Apple later fixed. So no, CXPatcher won't ever work on Ventura (kinda moot as Sonoma is a month or so away).

**Comment by mferrier** [comment]
@ultratiem  okay, thanks for the response

**Comment by Bentheminernz** [comment]
> I'm not upgrading to 13 or any higher version. Is someone gonna port this to macOS 12?

Why don't you want macOS ventura?

**Comment by italomandara** [comment]
closing this for not being a CXPatcher bug if you have further questions please use https://github.com/italomandara/CXPatcher/discussions
