### ISSUE TITLE
Mafia 3 Definitive Edition (Flickering Textures)

### ISSUE THREAD

**Issue by Jepl4r** [italomandara/CXPatcher#93]
I don't know if this is related to CXPacther or solely to GPTK 1.0.3, but the textures flickers in black and models sometimes disappear. It didn't happen before with GPTK 1.0.2

![Screenshot 2023-08-02 alle 23 57 00](https://github.com/italomandara/CXPatcher/assets/115885800/008c2f37-0912-4b77-b140-32bde16737f8)

**Comment by Jepl4r** [comment]
Mafia 1 has the same problem. Only Magia 2 seems to work correctly.

**Comment by Jepl4r** [comment]
Creating a new bottle doesn't solve the issue

**Comment by italomandara** [comment]
If you installed GPTK this can't be fixed and yes is due solely to GPTK 1.0.3.

**Comment by Jepl4r** [comment]
I also tried with DXVK. The game starts fine, but after something like 5 to 10 minutes it flickers too.

**Comment by Jepl4r** [comment]
After many tries, using DXVK works again. Still don't know what caused the issue.
