### ISSUE TITLE
You can’t open the application “CXPatcher” because this application is not supported on this Mac.

### ISSUE THREAD

**Issue by Naozumi520** [italomandara/CXPatcher#96]
Intel users want CXPatcher support as well :(

Crossover support x86 also

**Comment by italomandara** [comment]
I'll provide updated universal binaries soon

**Comment by italomandara** [comment]
@Naozumi520 please re-download the binary from the V0.2.22 release and close if your issue is solved

**Comment by Naozumi520** [comment]
Yep it's now working, thanks!
